<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="footprint_vertical_offset" value="-0.05" />

  <!-- Chassis -->
  <property name="chassis_height" value="0.1" />
  <property name="chassis_width" value="0.3" />
  <property name="chassis_length" value="0.6" />
  <property name="chassis_mass" value="5" /> <!-- in kg-->

  <!-- Wheels -->
  <xacro:property name="wheel_horizontal_separation" value="0.15" />
  <xacro:property name="wheel_vertical_separation" value="0.23" />
  <xacro:property name="wheel_vertical_offset" value="-0.13" />
  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
        iyy="0.0001" iyz="0.0"
        izz="0.0001" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
    </link>

    <gazebo reference="base_footprint">
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="chassis_link" />
  </joint>

  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="0 0 0"/>
      <geometry>
	<mesh filename="package://simple_robot_description_4wheels/meshes/inno_sim.stl"/>
        <!--<box size="${chassis_length} ${chassis_width} ${chassis_height}"/>-->
      </geometry>
      <material name="Grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${footprint_vertical_offset}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
    <!-- Center of mass -->
    <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
    <mass value="16.523"/>
    <!-- Moments of inertia: ( chassis without wheels ) -->
    <inertia
      ixx="0.3136" ixy="-0.0008" ixz="0.0164"
      iyy="0.3922" iyz="-0.0009"
      izz="0.4485"/>
    </inertial>
  </link>

  <gazebo reference="chassis_link">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Start of Wheels
  -->

  <xacro:macro name="wheel" params="prefix trans_x trans_y trans_z">

  <link name="${prefix}_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="Red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.477"/>
      <inertia
        ixx="0.0013" ixy="0" ixz="0"
        iyy="0.0024" iyz="0"
        izz="0.0013"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel">
      <!--<mu1>10</mu1>
      <mu2>10</mu2>-->
      <material>Gazebo/Red</material>
    </gazebo>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel" />
      <origin xyz="${trans_x} ${trans_y} ${trans_z}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
    </joint>

  </xacro:macro>

  <xacro:wheel prefix="front_left" trans_x="${wheel_horizontal_separation}" trans_y="${wheel_vertical_separation+wheel_width/2}" trans_z="${wheel_vertical_offset}"/>
  <xacro:wheel prefix="front_right" trans_x="${wheel_horizontal_separation}" trans_y="${-wheel_vertical_separation-wheel_width/2}" trans_z="${wheel_vertical_offset}"/>
  <xacro:wheel prefix="rear_left" trans_x="${-wheel_horizontal_separation}" trans_y="${wheel_vertical_separation+wheel_width/2}" trans_z="${wheel_vertical_offset}"/>
  <xacro:wheel prefix="rear_right" trans_x="${-wheel_horizontal_separation}" trans_y="${-wheel_vertical_separation-wheel_width/2}" trans_z="${wheel_vertical_offset}"/>
    
  <!-- End of Wheels
  -->

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0.262 0 0.1" rpy="0 0 0"/>
    <parent link="chassis_link"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://simple_robot_description_2wheels/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


  <!-- Bring in simulation data for Gazebo. -->
  <xacro:include filename="$(find simple_robot_description_4wheels)/urdf/robot_4wheels.gazebo" />

</robot>
